kotlin.code.style=official
org.gradle.jvmargs=-Xmx1g -Dfile.encoding=UTF-8
org.gradle.caching=true

signAllPublications=true

#kotlin.compiler.plugin.devkit.minCliVersion=2.3.20
#kotlin.compiler.plugin.devkit.includeBetaAndRc=latest
#kotlin.compiler.plugin.devkit.minIdeaVersion=261
#kotlin.compiler.plugin.devkit.includeIdeaRc=true
#kotlin.compiler.plugin.devkit.includeIdeaEap=true
#kotlin.compiler.plugin.devkit.useLatestDev=true
kotlin.compiler.plugin.devkit.companionLibraries=:plugin-annotations
kotlin.compiler.plugin.devkit.compilerPlugin=:compiler-plugin
