

package io.github.kyay10.wither.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link io.github.kyay10.wither.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/both/box")
@TestDataPath("$PROJECT_ROOT")
public class ContextJvmBoxTestGenerated extends AbstractContextJvmBoxTest {
  private void run(String fileName) {
    runTest("compiler-plugin/testData/both/box/" + fileName);
  }

  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/both/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("conditionals.kt")
  public void testConditionals() {
    run("conditionals.kt");
  }

  @Test
  @TestMetadata("conditionals2.kt")
  public void testConditionals2() {
    run("conditionals2.kt");
  }

  @Test
  @TestMetadata("generics.kt")
  public void testGenerics() {
    run("generics.kt");
  }

  @Test
  @TestMetadata("multiple.kt")
  public void testMultiple() {
    run("multiple.kt");
  }

  @Test
  @TestMetadata("multiple2.kt")
  public void testMultiple2() {
    run("multiple2.kt");
  }

  @Test
  @TestMetadata("nestedFunctions.kt")
  public void testNestedFunctions() {
    run("nestedFunctions.kt");
  }

  @Test
  @TestMetadata("nestedFunctions2.kt")
  public void testNestedFunctions2() {
    run("nestedFunctions2.kt");
  }

  @Test
  @TestMetadata("nestedFunctions3.kt")
  public void testNestedFunctions3() {
    run("nestedFunctions3.kt");
  }

  @Test
  @TestMetadata("simple.kt")
  public void testSimple() {
    run("simple.kt");
  }

  @Test
  @TestMetadata("smartcast.kt")
  public void testSmartcast() {
    run("smartcast.kt");
  }

  @Test
  @TestMetadata("subtype.kt")
  public void testSubtype() {
    run("subtype.kt");
  }
}
