

package io.github.kyay10.wither.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link io.github.kyay10.wither.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/both/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class WithJvmDiagnosticTestGenerated extends AbstractWithJvmDiagnosticTest {
  private void run(String fileName) {
    runTest("compiler-plugin/testData/both/diagnostics/" + fileName);
  }

  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/both/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("ambiguous.kt")
  public void testAmbiguous() {
    run("ambiguous.kt");
  }

  @Test
  @TestMetadata("conditionals.kt")
  public void testConditionals() {
    run("conditionals.kt");
  }
}
